Cache: s/SSH_PRIVATE_KEY_PATH/SEMAPHORE_CACHE_PRIVATE_KEY_PATH/g

diff --git a/cache b/cache
--- a/cache
+++ b/cache
@@ -214,7 +214,7 @@ cache::download_keys() {
   command="cls --sort=date"
   file=$1
 
-  output=$(echo -e "${command}" | lftp sftp://$SEMAPHORE_CACHE_USERNAME:DUMMY@$SEMAPHORE_CACHE_URL -e 'set sftp:connect-program "ssh -a -x -i '"${SSH_PRIVATE_KEY_PATH}"'"' 2>&1)
+  output=$(echo -e "${command}" | lftp sftp://$SEMAPHORE_CACHE_USERNAME:DUMMY@$SEMAPHORE_CACHE_URL -e 'set sftp:connect-program "ssh -a -x -i '"${SEMAPHORE_CACHE_PRIVATE_KEY_PATH}"'"' 2>&1)
 
   echo -e "$output" > $file
 }
@@ -275,7 +275,7 @@ cache::lftp() {
     cache::err "LFTP command can't be empty!"
   fi
 
-  command_log=$(echo -e "${lftp_command}" | lftp sftp://$SEMAPHORE_CACHE_USERNAME:DUMMY@$SEMAPHORE_CACHE_URL -e 'set sftp:connect-program "ssh -a -x -i '"${SSH_PRIVATE_KEY_PATH}"'"' 2>&1)
+  command_log=$(echo -e "${lftp_command}" | lftp sftp://$SEMAPHORE_CACHE_USERNAME:DUMMY@$SEMAPHORE_CACHE_URL -e 'set sftp:connect-program "ssh -a -x -i '"${SEMAPHORE_CACHE_PRIVATE_KEY_PATH}"'"' 2>&1)
   command_status=$?
 
   if [[ "${print_log}" == "with_logs" ]] && [ -n "$command_log" ]; then
@@ -364,22 +364,22 @@ cache::print_usage() {
 ################################################################################
 # Cheks the presence of the SSH key which is used to access the cache storage
 # Globals:
-#   SSH_PRIVATE_KEY_PATH
+#   SEMAPHORE_CACHE_PRIVATE_KEY_PATH
 # Arguments:
 #   none
 # Returns:
 #   none
 ################################################################################
 cache::check_ssh_key() {
-  if ! [[ -e $SSH_PRIVATE_KEY_PATH ]]; then
-    cache::err "Private SSH key missing! (${SSH_PRIVATE_KEY_PATH})"
+  if ! [[ -e $SEMAPHORE_CACHE_PRIVATE_KEY_PATH ]]; then
+    cache::err "Private SSH key missing! (${SEMAPHORE_CACHE_PRIVATE_KEY_PATH})"
   fi
 }
 
 ################################################################################
 # Loads the private SSH key into the agent
 # Globals:
-#   SSH_PRIVATE_KEY_PATH
+#   SEMAPHORE_CACHE_PRIVATE_KEY_PATH
 # Arguments:
 #   none
 # Returns:
@@ -392,7 +392,7 @@ cache::load_ssh_key() {
     cache::log "Loading SSH key into the agent"
   fi
 
-  ssh_agent_log=$(eval $(ssh-agent) 2>&1 && ssh-add <(cat ${SSH_PRIVATE_KEY_PATH}) 2>&1)
+  ssh_agent_log=$(eval $(ssh-agent) 2>&1 && ssh-add <(cat ${SEMAPHORE_CACHE_PRIVATE_KEY_PATH}) 2>&1)
 
   if ! [[ $? = 0 ]]; then
     cache::err "Error while configuring the SSH agent!\nLog: ${ssh_agent_log}"
@@ -427,7 +427,7 @@ cache::check_lftp() {
 # Globals:
 #   SEMAPHORE_CACHE_URL
 #   SEMAPHORE_CACHE_USERNAME
-#   SSH_PRIVATE_KEY_PATH
+#   SEMAPHORE_CACHE_PRIVATE_KEY_PATH
 # Arguments:
 #   none
 # Returns:
@@ -446,8 +446,8 @@ cache::check_env() {
     cache::err "'SEMAPHORE_CACHE_USERNAME' environment variable not set!"
   fi
 
-  if [[ -z $SSH_PRIVATE_KEY_PATH ]]; then
-    cache::err "'SSH_PRIVATE_KEY_PATH' environment variable not set!"
+  if [[ -z $SEMAPHORE_CACHE_PRIVATE_KEY_PATH ]]; then
+    cache::err "'SEMAPHORE_CACHE_PRIVATE_KEY_PATH' environment variable not set!"
   fi
 }
 
