fix failing checkout --use-cache when archive is corrupted

diff --git a/cache b/cache
--- a/cache
+++ b/cache
@@ -694,10 +694,18 @@ cache::lftp_get() {
 
     if [[ "$restored_path" = /* ]]; then
       echo "cache_total_rate 1" >> /tmp/toolbox_metrics
-      tar xzPf /tmp/$key -C . || echo "cache_corruption_rate 1" >> /tmp/toolbox_metrics
+      tar xzPf /tmp/$key -C .
+      if [[ $? -ne "0" ]]; then
+        echo "cache_corruption_rate 1" >> /tmp/toolbox_metrics
+        cache::err "Failed to restore the key.."
+      fi
     else
      echo "cache_total_rate 1" >> /tmp/toolbox_metrics
-      tar xzf /tmp/$key -C . || echo "cache_corruption_rate 1" >> /tmp/toolbox_metrics
+      tar xzf /tmp/$key -C .
+      if [[ $? -ne "0" ]]; then
+        echo "cache_corruption_rate 1" >> /tmp/toolbox_metrics
+        cache::err "Failed to restore the key.."
+      fi
     fi
     archive_size=$(ls -l /tmp/$key | awk '{print $5}')
     rm -rf /tmp/$key
@@ -706,6 +714,7 @@ cache::lftp_get() {
     cache::log "Key '$key' does not exist in the cache store."
   fi
 }
+
 
 ################################################################################
 # Wrapper around LFTP
@@ -933,6 +942,9 @@ cache::is_not_empty() {
 ################################################################################
 cache::err() {
   echo -e "\n! [$(date +"${DATE_FORMAT}")]: $@\n" >&2
+  if [ -n "$CACHE_FAIL_ON_ERROR" ]; then
+    exit 1
+  fi
 }
 
 cache::warn() {
