test

diff --git a/cache b/cache
--- a/cache
+++ b/cache
@@ -125,9 +125,9 @@ cache::restore() {
   while [[ $# -gt 0 ]]; do
     case "$1" in
       "-k" | "--key")
-        SEMAPHORE_CACHE_KEY=$2
+        SEMAPHORE_CACHE_KEYS=$2
 
-        if [[ -z $SEMAPHORE_CACHE_KEY ]]; then
+        if [[ -z $SEMAPHORE_CACHE_KEYS ]]; then
           cache::err "Cache key can't be empty!"
         fi
 
@@ -138,7 +138,14 @@ cache::restore() {
     esac
   done
 
-  cache::lftp_get
+  # looping and getting
+  for cache_key in ${SEMAPHORE_CACHE_KEYS//,/ }; do
+    echo "XXX KEY: ${cache_key}"
+    cache::key_matches_something ${cache_key} && echo "Postoji nesto" || echo "NE"
+
+  done
+
+  #cache::lftp_get
 }
 
 ################################################################################
@@ -223,6 +230,43 @@ cache::lftp_get() {
   fi
 }
 
+################################################################################
+# Wrapper around LFTP
+# Globals:
+#   E_FLMSNG
+#   E_NOSFL
+#   W_FLAEX
+#   SEMAPHORE_CACHE_URL
+#   SEMAPHORE_CACHE_USERNAME
+# Arguments:
+#   command
+#   log - when set to "with_logs" it prints command output log
+# Returns:
+#   None
+################################################################################
+cache::new_lftp() {
+  local lftp_command
+  local print_log
+  local command_log
+  local command_status
+
+  lftp_command=$1
+  print_log=${2:-false}
+
+  echo "COMMAND: $lftp_command"
+
+  if [[ -z $lftp_command ]]; then
+    cache::err "LFTP command can't be empty!"
+  fi
+
+  command_log=$(echo -e "${lftp_command}" | lftp -u $SEMAPHORE_CACHE_USERNAME, sftp://$SEMAPHORE_CACHE_URL 2>&1)
+  command_status=$?
+
+  echo "COMMAND LOG: $command_log"
+  echo "COMMAND STATUS: $command_status"
+
+  return $command_status
+}
 
 ################################################################################
 # Wrapper around LFTP
@@ -464,6 +508,29 @@ cache::file_is_present() {
     true
   fi
 }
+
+################################################################################
+# Helper function to check if file is present on cache directory
+# Globals:
+#   E_FLMSNG
+# Arguments:
+#   key (file name)
+# Returns:
+#   true or false
+################################################################################
+cache::key_matches_something() {
+  local KEY
+
+  KEY=$1
+
+  echo "KEY IS: $KEY"
+  if [[ $VERBOSE_LOG == 0 ]]; then
+    cache::log "Checking if key $KEY is present in cache store."
+  fi
+
+  cache::new_lftp "glob --exist ${KEY}"
+}
+
 
 ################################################################################
 # Helper function to check if file is present on cache directory
