Don't include SPC into Mac releases

diff --git a/install-toolbox b/install-toolbox
--- a/install-toolbox
+++ b/install-toolbox
@@ -105,29 +105,30 @@ else
   echo "toolbox_install_error{module='artifacts'} 1" >> /tmp/toolbox_metrics
 fi
 
-
-echo "Installing the artifacts CLI"
-install_cmd mv ~/.toolbox/spc $INSTALL_PATH/spc
-install_cmd chmod +x $INSTALL_PATH/spc
-if [[ $? -eq 0 ]];then
-  echo "spc installed"
-else
-  echo "toolbox_install_error{module='spc'} 1" >> /tmp/toolbox_metrics
-fi
-
-echo "Installing the when CLI"
-install_cmd mv ~/.toolbox/when $INSTALL_PATH/when
-install_cmd chmod +x $INSTALL_PATH/when
-if [[ $? -eq 0 ]];then
-  echo "when installed"
-else
-  echo "toolbox_install_error{module='when'} 1" >> /tmp/toolbox_metrics
-fi
-
-
 if [[ `uname` != "Darwin" ]]; then
+
+  echo "Installing the SPC CLI"
+  install_cmd mv ~/.toolbox/spc $INSTALL_PATH/spc
+  install_cmd chmod +x $INSTALL_PATH/spc
+  if [[ $? -eq 0 ]];then
+    echo "spc installed"
+  else
+    echo "toolbox_install_error{module='spc'} 1" >> /tmp/toolbox_metrics
+  fi
+
+  echo "Installing the when CLI"
+  install_cmd mv ~/.toolbox/when $INSTALL_PATH/when
+  install_cmd chmod +x $INSTALL_PATH/when
+  if [[ $? -eq 0 ]];then
+    echo "when installed"
+  else
+    echo "toolbox_install_error{module='when'} 1" >> /tmp/toolbox_metrics
+  fi
+
   echo "Starting to collect System Metrics in /tmp/system-metrics"
-  sh ~/.toolbox/system-metrics-collector & # failure won't be propagated to the caller in case of using &
+
+  # failure won't be propagated to the caller in case of using &
+  sh ~/.toolbox/system-metrics-collector &
 fi
 
 echo "toolbox_install_total 1" >> /tmp/toolbox_metrics
