self-hosted: install spc/when

diff --git a/install-self-hosted-toolbox b/install-self-hosted-toolbox
--- a/install-self-hosted-toolbox
+++ b/install-self-hosted-toolbox
@@ -64,4 +64,23 @@ else
   echo "Error installing retry at $INSTALL_PATH/retry"
 fi
 
+echo "Installing the SPC CLI"
+install_cmd mv ~/.toolbox/spc $INSTALL_PATH/spc
+install_cmd chmod +x $INSTALL_PATH/spc
+if [[ $? -eq 0 ]];then
+  echo "spc installed"
+else
+  echo "Error installing spc at $INSTALL_PATH/spc"
+fi
+
+
+echo "Installing the when CLI"
+install_cmd mv ~/.toolbox/when $INSTALL_PATH/when
+install_cmd chmod +x $INSTALL_PATH/when
+if [[ $? -eq 0 ]];then
+  echo "when installed"
+else
+  echo "Error installing when at $INSTALL_PATH/when"
+fi
+
 source ~/.toolbox/toolbox && echo 'source ~/.toolbox/toolbox' >> ~/.bash_profile
