Sem context (#356)
* Introduce new sem-context cli tool (only for hosted agents)
* Update artifact cli tool to v0.6.0

Co-authored-by: Igor Šarčević <igor@renderedtext.com>

diff --git a/install-toolbox b/install-toolbox
--- a/install-toolbox
+++ b/install-toolbox
@@ -58,6 +58,14 @@ else
   echo "toolbox_install_error{module='cache'} 1" >> /tmp/toolbox_metrics
 fi
 
+install_cmd ln -sf ~/.toolbox/sem-context $INSTALL_PATH/sem-context
+install_cmd chmod +x $INSTALL_PATH/sem-context
+if [[ $? -eq 0 ]];then
+  echo "sem-context installed"
+else
+  echo "toolbox_install_error{module='sem-context'} 1" >> /tmp/toolbox_metrics
+fi
+
 install_cmd ln -sf ~/.toolbox/sem-service $INSTALL_PATH/sem-service
 install_cmd chmod +x $INSTALL_PATH/sem-service
 if [[ $? -eq 0 ]];then
