libcheckout: Fail if branch is missing but sha exist on a different branch (#398)
* Add tests to reproduce missing branch and existing sha issue

* libcheckout: Fail if branch is missing buth sha exist on a different branch

diff --git a/libcheckout b/libcheckout
--- a/libcheckout
+++ b/libcheckout
@@ -165,6 +165,14 @@ function checkout::checkrevision {
   fi
 }
 
+function checkout::branch_checkout {
+  git checkout -f "$SEMAPHORE_GIT_BRANCH"
+  if [ $? -ne 0 ]; then
+    echo "Branch: ${SEMAPHORE_GIT_BRANCH} not found .... Exiting"
+    return 1
+  fi
+}
+
 function checkout::shallow() {
   if [ -z ${SEMAPHORE_GIT_DEPTH:-""} ]; then
     SEMAPHORE_GIT_DEPTH=50
@@ -174,7 +182,11 @@ function checkout::shallow() {
   if [ $? -ne 0 ]; then
     echo "Branch not found performing full clone"
     git clone $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR
-    cd $SEMAPHORE_GIT_DIR
+    cd "$SEMAPHORE_GIT_DIR"
+    checkout::branch_checkout
+    if [ $? -ne 0 ]; then
+      return 1
+    fi
     checkout::checkrevision
     if [ "$?" -eq "0" ]; then
       git reset --hard $SEMAPHORE_GIT_SHA 2>/dev/null
