ref based checkout

diff --git a/libcheckout b/libcheckout
--- a/libcheckout
+++ b/libcheckout
@@ -9,6 +9,11 @@ function checkout() {
     return 1
   fi
 
+  if [ -n "$SEMAPHORE_GIT_REF_TYPE" ]; then
+    checkout::refbased
+    return 0
+  fi
+
   if [ "$1" = "--use-cache" ]; then
     echo "[Experimental stability] Using cached Git repository."
     checkout::use_cache
@@ -149,6 +154,35 @@ function checkout::shallow() {
       git reset --hard $SEMAPHORE_GIT_SHA
     fi
   fi
+}
+
+function checout::refbased() {
+  if [ -z ${SEMAPHORE_GIT_DEPTH} ]; then
+    SEMAPHORE_GIT_DEPTH=50
+  fi
+
+  if [ $SEMAPHORE_GIT_REF_TYPE = "pull-request"]; then
+    git clone --depth $SEMAPHORE_GIT_DEPTH $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>/dev/null
+    cd $SEMAPHORE_GIT_DIR
+    git fetch origin +$SEMAPHORE_GIT_REF:
+    git checkout -qf FETCH_HEAD
+
+    exit 0
+  fi
+
+  if [ $SEMAPHORE_GIT_REF_TYPE = "tag"]; then
+    git clone --depth $SEMAPHORE_GIT_DEPTH -b $SEMAPHORE_GIT_TAG_NAME $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>/dev/null
+    if [ $? -ne 0 ]; then
+      echo "Tag $SEMAPHORE_GIT_TAG_NAME not found"
+      exit 1
+    fi
+    cd $SEMAPHORE_GIT_DIR
+    git checkout -qf $SEMAPHORE_GIT_TAG_NAME
+
+    exit 0
+  fi
+
+  checkout::shallow
 }
 
 export -f checkout
