Fix checkout for tag refs (#68)
* fix refs/tags checkout error

* update tests

diff --git a/libcheckout b/libcheckout
--- a/libcheckout
+++ b/libcheckout
@@ -122,12 +122,21 @@ function checkout::shallow() {
   if [ -z ${SEMAPHORE_GIT_DEPTH} ]; then
     SEMAPHORE_GIT_DEPTH=50
   fi
-  git clone --depth $SEMAPHORE_GIT_DEPTH -b $SEMAPHORE_GIT_BRANCH $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR
-  cd $SEMAPHORE_GIT_DIR
-  git reset --hard $SEMAPHORE_GIT_SHA 2>/dev/null
+  echo "Performin shallow clone with depth: $SEMAPHORE_GIT_DEPTH"
+  git clone --depth $SEMAPHORE_GIT_DEPTH -b $SEMAPHORE_GIT_BRANCH $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>/dev/null
   if [ $? -ne 0 ]; then
-    git fetch --unshallow
-    git reset --hard $SEMAPHORE_GIT_SHA
+    echo "Branch not found perfoming full clone"
+    git clone $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR
+    cd $SEMAPHORE_GIT_DIR
+    git reset --hard $SEMAPHORE_GIT_SHA 2>/dev/null
+  else
+    cd $SEMAPHORE_GIT_DIR
+    git reset --hard $SEMAPHORE_GIT_SHA 2>/dev/null
+    if [ $? -ne 0 ]; then
+      "SHA: $SEMAPHORE_GIT_SHA not found perfoming full clone"
+      git fetch --unshallow
+      git reset --hard $SEMAPHORE_GIT_SHA
+    fi
   fi
 }
 
