more tests

diff --git a/libcheckout b/libcheckout
--- a/libcheckout
+++ b/libcheckout
@@ -142,15 +142,15 @@ function checkout::shallow() {
     git clone $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR
     cd $SEMAPHORE_GIT_DIR
     checkout::checkrevision
-    git reset --hard $SEMAPHORE_GIT_SHA 2>/dev/null
+    git checkout -qf $SEMAPHORE_GIT_SHA 2>/dev/null
   else
     cd $SEMAPHORE_GIT_DIR
-    git reset --hard $SEMAPHORE_GIT_SHA 2>/dev/null
+    git checkout -qf $SEMAPHORE_GIT_SHA 2>/dev/null
     if [ $? -ne 0 ]; then
       echo "SHA: $SEMAPHORE_GIT_SHA not found performing full clone"
       git fetch --unshallow
       checkout::checkrevision
-      git reset --hard $SEMAPHORE_GIT_SHA
+      git checkout -qf $SEMAPHORE_GIT_SHA 2>/dev/null
     fi
   fi
 }
@@ -172,6 +172,7 @@ function checkout::refbased() {
     else
       git checkout -qf FETCH_HEAD
       echo "HEAD is now at $SEMAPHORE_GIT_SHA"
+
       exit 0
     fi
   fi
@@ -179,13 +180,16 @@ function checkout::refbased() {
   if [ $SEMAPHORE_GIT_REF_TYPE = "tag" ]; then
     git clone --depth $SEMAPHORE_GIT_DEPTH -b $SEMAPHORE_GIT_TAG_NAME $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>/dev/null
     if [ $? -ne 0 ]; then
-      echo "Tag $SEMAPHORE_GIT_TAG_NAME not found"
-      exit 1
-    fi
-    cd $SEMAPHORE_GIT_DIR
-    git checkout -qf $SEMAPHORE_GIT_TAG_NAME
+      echo "Release $SEMAPHORE_GIT_TAG_NAME not found .... Exiting"
 
-    exit 0
+      exit 1
+    else
+      cd $SEMAPHORE_GIT_DIR
+      git checkout -qf $SEMAPHORE_GIT_TAG_NAME
+      echo "HEAD is now at ${SEMAPHORE_GIT_SHA} Release ${SEMAPHORE_GIT_TAG_NAME}"
+
+      exit 0
+    fi
   fi
 
   checkout::shallow
