Print stderr in case clone fails and add toolbox functions to retry commands

diff --git a/libcheckout b/libcheckout
--- a/libcheckout
+++ b/libcheckout
@@ -170,10 +170,10 @@ function checkout::shallow() {
     SEMAPHORE_GIT_DEPTH=50
   fi
   echo "Performing shallow clone with depth: $SEMAPHORE_GIT_DEPTH"
-  git clone --depth $SEMAPHORE_GIT_DEPTH -b $SEMAPHORE_GIT_BRANCH $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>/dev/null
+  output=$(git clone --depth $SEMAPHORE_GIT_DEPTH -b $SEMAPHORE_GIT_BRANCH $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>&1)
   if [ $? -ne 0 ]; then
-    echo "Branch not found performing full clone"
-    git clone $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR
+    echo -e "$output \nBranch not found performing full clone"
+    git clone $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>&1
     cd $SEMAPHORE_GIT_DIR
     checkout::checkrevision
     if [ "$?" -eq "0" ]; then
@@ -205,7 +205,12 @@ function checkout::refbased() {
   fi
 
   if [ ${SEMAPHORE_GIT_REF_TYPE:-""} = "pull-request" ]; then
-    git clone --depth $SEMAPHORE_GIT_DEPTH $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>/dev/null
+    output=$(git clone --depth $SEMAPHORE_GIT_DEPTH $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>&1)
+    if [ $? -ne 0 ]; then
+      echo "$output Pull request not found .... Exiting"
+
+      return 1
+    fi
     cd $SEMAPHORE_GIT_DIR
     git fetch origin +$SEMAPHORE_GIT_REF: 2>/dev/null
     if [ $? -ne 0 ]; then
@@ -221,9 +226,9 @@ function checkout::refbased() {
   fi
 
   if [ ${SEMAPHORE_GIT_REF_TYPE:-""} = "tag" ]; then
-    git clone --depth $SEMAPHORE_GIT_DEPTH -b $SEMAPHORE_GIT_TAG_NAME $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>/dev/null
+    output=$(git clone --depth $SEMAPHORE_GIT_DEPTH -b $SEMAPHORE_GIT_TAG_NAME $SEMAPHORE_GIT_URL $SEMAPHORE_GIT_DIR 2>&1)
     if [ $? -ne 0 ]; then
-      echo "Release $SEMAPHORE_GIT_TAG_NAME not found .... Exiting"
+      echo -e "$output \nRelease $SEMAPHORE_GIT_TAG_NAME not found .... Exiting"
 
       return 1
     else
